language: ruby
rvm:
- 2.6.3
install:
  - bundle install
script:
  - yaml-lint _data/
  - "./script/ci-build $TRAVIS_TAG"
deploy:
  provider: script
  script: bash script/deploy.sh
  on:
    tags: true
    branch: staging

branches:
  only:
    - staging
    - /\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Q2y4lVummKf7SHBUmouAnAr9S9h2Y2IpNZa0xWUVjATEu1ulHRobr8PLU7Cm5jfsHjRpTEpw++bb1/tsOauiA5ieHx5cZ1EqBeieVTIX724sl9oy71cR4dgvys3pM9C8VQD52SXiLo20QjZ/k+DYaRUBRhyrwy3IRARlVw+OiO+TrzGu7hdN7nDzJfliUvIUbi2jtkq1fvpS0bxsZ9Qvo4/BBWq6rAVbBRmzFEa9gv/rU+enkL0zgHzslYPMAi34Rpnahshs3TcGG1tBIsLQfOyquhpwsI6fPRjlcXjPxdFWn90Qv1ITwLAmDhUPtJKpi0+8XaHdb6j09+LpAIdznrPvhS00uGSooXrLf3YcY7lL3vpaxaaZv/upDz7cpLVQq1YQR0O8FYAaQLuQJ1/XzRhjELuMWpF8lnWv83DRtslSLlfIelxlHpiT1zL9XAzlTtygm/9XzzL7e79QL4zliwfrY+ZBKlqT5PzNypljtaj7+0Nbuw0Jnz3mRIov2T0DD56vVU5AcbJDL4j0W2JNjbLcrNH0KLGEYaO9shoRKfQfDiKtarShFBo41tmKkcfGJ+70oT+FMKfS8NPBfu9cq0erLqs8Y3Wk4Kr7B1PBBALnnPT42CLi4xT5zOw9J7q+AliBLkKl38eV/Atn19XMfp1yf8RFpjmxTkdB0BTqWKg=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
