# standard jekyll configuration
title: rasta.online
url: "http://Rasta.Online"
baseurl: ""

markdown: kramdown
highlighter: pygments

excerpt_separator: <!--more-->

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
path-partner: "http://rasta.online/library/partner"
email: info@rasta.online
description: teamwork make dreams work
cv: "https://careers.stackoverflow.com/jenskrause"
skype: al0b4r
fb-user: www.rasta.online
fb-url: "https://www.facebook.com/www.rasta.online"
git-url: "https://github.com/Solomonic"
