# standard jekyll configuration
title: rasta.online
url: "https://Rasta.Online"
name: Duppy conqueror in the digital jungle.
baseurl: ""
author: "Ras Yen"

markdown: kramdown
highlighter: rouge

destination: docs

excerpt_separator: <!--more-->

sass:
  style: compressed

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
path-image: "http://rasta.online/library/images"
email: info@rasta.online
description: Interested in Rasta, Reggae or creating websites and internet technologies, open-source and team-management?
git-url: "https://github.com/RapidAgileSoftware"
instagram-url: "https://instagram.com/ras.yen"
linked_in-url: "https://www.linkedin.com/in/jens-krause-2a88901a6"
company-url: https://RapidAgileSoftware.github.io

fb-user: www.rasta.online
fb-url: "https://www.facebook.com/www.rasta.online"
fb-app-id: 172683489748870

addthis: true

jekyll_doc: "http://jekyllrb.com/docs"

#set defaults
defaults:
  -
    scope:
      path: ""
    values:
      keywords: [ Rasta, Rastafari, Rasta Livety, Lion of Judah, Ganja, Jah, Reggae, Rastaman, Empress, King, Haile Selassie, Lion of Judah, Music, Internet, SEO, OpenSource, Programming]
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: rasta
      author: Jens Krause
      keywords: [ Software Development, Open Source, Free Tools, SEO, Performance, continuous integration, coding, programming]
  -
    scope:
      path: "library/**"
    values:
      sitemap: false
  -
    scope:
      path: "shop"
    values:
      lightbox: true
  -
    scope:
      path: "music"
    values:
      carousel: true
      video: true
      keywords: [ Rasta, Rastafari, Rasta Livety, Ganja, Jah, Reggae, Music, Ragga, Artists, Videos, Rastaman, Empress, King, Haile Selassie, Lion of Judah]

page_gen:
- data: 'artists'
  template: 'artist'
  name: 'name'
  title: 'name'
  dir: 'music/artist'
- data: 'shop_categories'
  template: 'shop_category'
  name: 'title'
  title: 'title'
  dir: 'shop/category'


  strip: true
  base_path: library/images
  output_path_format: library/images/resized/%{width}/%{basename}
  cache: true

picture:
  source: "library/images"
  output: "library/images/generated"
  suppress_warnings: true
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

jekyll-minifier:
  compress_css: true

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

plugins:
  - jekyll-datapage-generator
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-toc


