# Site settings
title: rasta.online
email: info@rasta.online
description: > # this means to ignore newlines until "baseurl:"
  teamwork make dreams work
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Rasta.Online" # the base hostname & protocol for your site
cv: "https://careers.stackoverflow.com/jenskrause"
skype: al0b4r
fb-user: www.rasta.online
fb-url: "https://www.facebook.com/www.rasta.online"


# Build settings
markdown: kramdown
highlighter: pygments

# standard jekyll configuration

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
