# standard jekyll configuration
title: rasta.online
url: "http://Rasta.Online"
baseurl: ""

markdown: kramdown
highlighter: pygments

excerpt_separator: <!--more-->

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
path-partner: "http://rasta.online/library/partner"
path-image: "http://rasta.online/library/images"
email: info@rasta.online
avatar: "http://rasta.online/images/avatar.png"
description: Interested in creating websites and internet technologies, open-source and team-management ? Browse our the educational articles abd tutorials.
cv: "https://careers.stackoverflow.com/jenskrause"
pingdom_url: "http://tools.pingdom.com/fpt/"
pingdom_report: "http://tools.pingdom.com/fpt/#!/bTZzor/rasta.online/about"
skype: al0b4r
fb-user: www.rasta.online
fb-url: "https://www.facebook.com/www.rasta.online"
git-url: "https://github.com/Solomonic"
jekyll_doc: "http://jekyllrb.com/docs"
