# Site settings
title: Mr.YenZa
email: mr.yenza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  teamwork make dreams work
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yenza.de" # the base hostname & protocol for your site
cv: "https://careers.stackoverflow.com/jenskrause"
skype: al0b4r

# Build settings
markdown: kramdown
highlighter: pygments

# standard jekyll configuration

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
