# standard jekyll configuration
title: rasta.online
url: "https://Rasta.Online"
name: Duppy conqueror in the digital jungle.
baseurl: "https://rasta.online"

markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
path-partner: "http://rasta.online/library/partner"
path-image: "http://rasta.online/library/images"
email: info@rasta.online
description: Interested in creating websites and internet technologies, open-source and team-management ? Browse our the educational articles and tutorials.
git-url: "https://github.com/Solomonic"
instagram-url: "https//instagram.com/ras.yen"
jekyll_doc: "http://jekyllrb.com/docs"

#set defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: rasta
