# standard jekyll configuration
title: rasta.online
url: "https://Rasta.Online"
name: Duppy conqueror in the digital jungle.
baseurl: ""

markdown: kramdown
highlighter: rouge

destination: docs

excerpt_separator: <!--more-->

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

# custom variables
path-image: "http://rasta.online/library/images"
email: info@rasta.online
description: Interested in Rasta, Reggae or creating websites and internet technologies, open-source and team-management?
git-url: "https://github.com/RapidAgileSoftware"
instagram-url: "https://instagram.com/ras.yen"
linked_in-url: "https://www.linkedin.com/in/jens-krause-2a88901a6"
company-url: https://RapidAgileSoftware.github.io

jekyll_doc: "http://jekyllrb.com/docs"

#set defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      share: rasta
  -
    scope:
      path: "library/**"
    values:
      sitemap: false

page_gen:
- data: 'artists'
  template: 'artist'
  name: 'name'
  title: 'name'
  dir: 'music/artist'


  strip: true
  base_path: library/images
  output_path_format: library/images/resized/%{width}/%{basename}
  cache: true

picture:
  source: "library/images"
  output: "library/images/generated"

jekyll-minifier:
  compress_css: true

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

plugins:
  - jekyll-datapage-generator
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-toc

