#!/usr/bin/env bash
#set -e # halt script on error

if [ -n $TRAVIS_TAG ]
then
	JEKYLL_ENV="production" bundle exec jekyll build
	git status
	git add .
	git commit -m"[skip travis] Automated build"
	git remote set-url origin https://$ROBOT@github.com/Solomonic/theming.rasta_online.git
	git push origin HEAD:master --force
else
	JEKYLL_ENV="production" bundle exec jekyll build
fi
